development:
  adapter: mysql2
  database: pollit_development
  username: root
  password: 
test:
  adapter: mysql2
  database: pollit_test
  username: root
  password: 

production:
  adapter: mysql2
  database: pollit_production
  username: root
  password: 
